### ISSUE TITLE
Service.ensure function will return true for all Optional values

### ISSUE THREAD

**Issue by brandontthompson** [brandontthompson/polyservice#1]
the ensure function will early exit and not validate the value type 
intended functionality is to check the type if an argument is passed and the type does not include the "any" type

https://github.com/brandontthompson/polyservice/blob/6c6e303de37ee57f120b5a484a5ad2c8a2c0ec9b/service.ts#L59

**Comment by zeepk** [comment]
I agree

**Comment by brandontthompson** [comment]
Resolved with commit 19e06e9535734849013bf6584f75af9c18648c19
